### ISSUE TITLE
获取trackId报错

### ISSUE THREAD

**Issue by NorthStar1226** [huaisha1224/jd-assistant#15]
获取trackid报错是什么情况啊，
VM402:3 Uncaught ReferenceError: getTakId is not defined
    at <anonymous>:3:15

**Comment by huaisha1224** [comment]
config.ini里面填写一下
config.ini的编码格式也需要注意下

**Comment by NorthStar1226** [comment]
在开发者工具里面获取trackid报错，我找了下js里面，trackID = $("#TrackID").val();用这个方法获取，获取到的值是TestTrackId，这个不对吧

**Comment by huaisha1224** [comment]
在订单支付页面；按F12、在查看器页面中搜索即可eid、fp、TrackID、riskControl

**Comment by AWoodenMan** [comment]
搜索了，搜到的TrackID的值就是TestTrackID，我在cookie中找到了TrackID，但是，运行脚本的时候，报这个错



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "huaisha1224/jd-assistant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 中午11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huaisha1224/jd-assistant] 获取trackId报错 (#15)





 
config.ini里面填写一下
 config.ini的编码格式也需要注意下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AWoodenMan** [comment]
运行报错，可我已经配置了啊
2021-09-24 11:56:46,148 ERROR: 请在 config.ini 中配置 eid, fp, track_id, risk_control 参数，具体请参考 wiki-常见问题
Traceback (most recent call last):
  File "D:\Project\Python\goudong\jd-assistant\main.py", line 13, in <module>
    asst = Assistant()  # 初始化
  File "D:\Project\Python\goudong\jd-assistant\jd_assistant.py", line 51, in __init__
    raise AsstException('请在 config.ini 中配置 eid, fp, track_id, risk_control 参数，具体请参考 wiki-常见问题')
exception.AsstException: 请在 config.ini 中配置 eid, fp, track_id, risk_control 参数，具体请参考 wiki-常见问题

**Comment by NorthStar1226** [comment]
我修改地址后 ，运行工程，怎么一直都是北京的地址，并且报异常exception: 'NoneType' object has no attribute 'get'

**Comment by rheatin** [comment]
riskControl value没有值怎么破 - -

**Comment by AWoodenMan** [comment]
VM1504:4
填这个

**Comment by NorthStar1226** [comment]
> riskControl value没有值怎么破 - -
VM1504:4
填这个

**Comment by rheatin** [comment]
> VM1504:4

成功了，棒棒，谢谢你~

**Comment by Supermanhu** [comment]
> > VM1504:4
> 
> 成功了，棒棒，谢谢你~

您好，请问可以教我一下么，我仍然不会获取config.ini中的四个参数

**Comment by huaisha1224** [comment]
在订单支付页面；按F12、在查看器页面中搜索即可eid、fp、TrackID、riskControl
如果riskControl value没有值怎么破 - -
填这个：VM1504:4

**Comment by Supermanhu** [comment]
> 在订单支付页面；按F12、在查看器页面中搜索分类eid、fp、TrackID、riskControl 如果riskControl值没有值怎么破 - - 填这个：VM1504:4

在elements搜索还是sources

**Comment by zhiliuliu1205** [comment]
我的也是testtrackid
> 在开发者工具里面获取trackid报错，我找了下js里面，trackID = $("#TrackID").val();用这个方法获取，获取到的值是TestTrackId，这个不对吧
