### ISSUE TITLE
参数无法获取

### ISSUE THREAD

**Issue by XiaoHb233** [huaisha1224/jd-assistant#2]
trackid 
risk_control
在结算页面，f12，网络那个数据搜索并获取不到
ps:作者接批量号定制吗

**Comment by huaisha1224** [comment]
在订单支付页面；按F12、在查看器页面中搜索即可eid、fp、TrackID、riskControl

**Comment by XiaoHb233** [comment]
> 在订单支付页面；按F12、在查看器页面中搜索即可eid、fp、TrackID、riskControl

trackid在Cookie里面看见了，network搜索数据riskcontrol搜不到

**Comment by XiaoHb233** [comment]
贴图一下，我把riskcontrol改为undefined，运行main.py,无法运行
![Uploading Screenshot_2021-09-07-18-29-19-962_com.tencent.mobileqq.jpg…]()

**Comment by XiaoHb233** [comment]
C:\Users\911>C:\Users\911\Desktop\jd-assistant-main\main.py
Traceback (most recent call last):
  File "C:\Users\911\Desktop\jd-assistant-main\main.py", line 3, in <module>
    from jd_assistant import Assistant
  File "C:\Users\911\Desktop\jd-assistant-main\jd_assistant.py", line 13, in <module>
    from config import global_config
  File "C:\Users\911\Desktop\jd-assistant-main\config.py", line 29, in <module>
    global_config = Config()
  File "C:\Users\911\Desktop\jd-assistant-main\config.py", line 12, in __init__
    raise FileNotFoundError("No such file: config.ini")
FileNotFoundError: No such file: config.ini

**Comment by huaisha1224** [comment]
track_id = 100016034400
risk_control = 100016034400
用这个试试

**Comment by XiaoHb233** [comment]
> track_id = 100016034400
> risk_control = 100016034400
> 用这个试试

运行主程序还是报错，代码上面我贴了

**Comment by huaisha1224** [comment]
报错提示没有找到config.ini
1、确认一下config.ini是否存在
2、如果存在的话、可以把目录移动到D盘 或者C盘根目录、不要放在中文目录中
